[2010-10-13 19:06:07,656] [INFO] from run_server in main at main.py:69 :
orzoj-server started, listening on 9351

[2010-10-13 19:06:09,187] [INFO] from run_server in main at main.py:82 :
connected by '127.0.0.1:36746'

[2010-10-13 19:06:10,004] [INFO] from run in work at work.py:397 :
[judge 'orzoj-judge-default'] successfully connected

[2010-10-13 19:06:21,454] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #4

[2010-10-13 19:06:21,483] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'a+b'

[2010-10-13 19:06:25,152] [WARNING] from _read in web at web.py:242 :
website requests relogin

[2010-10-13 19:07:18,740] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-10-13 19:07:18,740] [ERROR] from accept in snc at snc.py:78 :
socket error: error(4, 'Interrupted system call')

[2010-10-13 19:07:18,741] [DEBUG] from run_server in main at main.py:88 :
waiting for threads, current active count: 4

[2010-10-13 19:07:18,741] [DEBUG] from run_server in main at main.py:90 :
active thread: 'MainThread'

[2010-10-13 19:07:18,742] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_work'

[2010-10-13 19:07:18,742] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_new_judge_connection'

[2010-10-13 19:07:18,743] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work._thread_fetch_task'

