[2010-09-19 18:34:26,886] [INFO] from run_server in main at main.py:77 :
orzoj-server started, listening on 9351

[2010-09-19 18:34:29,225] [INFO] from run_server in main at main.py:89 :
connected by ('127.0.0.1', 52316)

[2010-09-19 18:34:29,441] [INFO] from run in work at work.py:345 :
judge 'orzoj-judge-default' connected successfully

[2010-09-19 18:34:50,442] [ERROR] from write_all in snc at snc.py:99 :
socket error: error(32, 'Broken pipe')

[2010-09-19 18:34:50,442] [WARNING] from run in work at work.py:354 :
failed to serve judge because of network error.

[2010-09-19 18:34:50,442] [INFO] from _clean in work at work.py:133 :
judge 'orzoj-judge-default' disconnected

[2010-09-19 18:34:50,443] [ERROR] from close in snc at snc.py:139 :
socket error: error(11, 'Resource temporarily unavailable')

[2010-09-19 18:34:56,628] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-19 18:34:56,629] [ERROR] from run_server in main at main.py:85 :
socket error: error(4, 'Interrupted system call')

[2010-09-19 18:34:56,629] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 4

[2010-09-19 18:34:56,629] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:34:56,630] [DEBUG] from run_server in main at main.py:97 :
active thread: 'work.thread_work'

[2010-09-19 18:34:56,630] [DEBUG] from run_server in main at main.py:97 :
active thread: 'work._thread_fetch_task'

[2010-09-19 18:34:56,630] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:34:57,631] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 3

[2010-09-19 18:34:57,631] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:34:57,631] [DEBUG] from run_server in main at main.py:97 :
active thread: 'work.thread_work'

[2010-09-19 18:34:57,631] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:34:58,633] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:34:58,633] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:34:58,633] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:34:59,634] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:34:59,635] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:34:59,635] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:00,156] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-19 18:35:00,156] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:00,157] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:00,157] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:00,468] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-19 18:35:00,469] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:00,469] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:00,469] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:00,660] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-19 18:35:00,660] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:00,660] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:00,661] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:00,820] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-19 18:35:00,820] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:00,820] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:00,821] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:01,012] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-19 18:35:01,012] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:01,012] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:01,013] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:02,014] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:02,014] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:02,014] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:03,016] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:03,016] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:03,016] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:04,017] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:04,018] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:04,018] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:05,020] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:05,020] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:05,020] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:06,021] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:06,022] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:06,022] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:07,022] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:07,023] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:07,023] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:08,024] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:08,025] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:08,025] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:09,025] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:09,026] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:09,026] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:10,026] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:10,027] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:10,027] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:11,028] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:11,029] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:11,029] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:12,029] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:12,030] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:12,030] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:13,030] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:13,031] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:13,031] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:14,032] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:14,033] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:14,033] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:15,034] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:15,034] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:15,034] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-19 18:35:16,035] [DEBUG] from run_server in main at main.py:95 :
waiting for threads, current active count: 2

[2010-09-19 18:35:16,036] [DEBUG] from run_server in main at main.py:97 :
active thread: 'MainThread'

[2010-09-19 18:35:16,036] [DEBUG] from run_server in main at main.py:97 :
active thread: 'Dummy-1'

[2010-09-22 10:09:23,543] [INFO] from run_server in main at main.py:69 :
orzoj-server started, listening on 9351

[2010-09-22 10:09:25,863] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-22 10:09:25,864] [ERROR] from accept in snc at snc.py:74 :
socket error: error(4, 'Interrupted system call')

[2010-09-22 10:09:25,864] [DEBUG] from run_server in main at main.py:88 :
waiting for threads, current active count: 3

[2010-09-22 10:09:25,864] [DEBUG] from run_server in main at main.py:90 :
active thread: 'MainThread'

[2010-09-22 10:09:25,865] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_work'

[2010-09-22 10:09:25,865] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work._thread_fetch_task'

[2010-09-22 10:09:38,134] [INFO] from run_server in main at main.py:69 :
orzoj-server started, listening on 9351

[2010-09-22 10:09:49,440] [INFO] from run_server in main at main.py:82 :
connected by '127.0.0.1:54054'

[2010-09-22 10:09:49,650] [INFO] from run in work at work.py:345 :
judge 'orzoj-judge-default' connected successfully

[2010-09-22 10:10:11,253] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-22 10:10:11,254] [ERROR] from accept in snc at snc.py:74 :
socket error: error(4, 'Interrupted system call')

[2010-09-22 10:10:11,254] [DEBUG] from run_server in main at main.py:88 :
waiting for threads, current active count: 4

[2010-09-22 10:10:11,254] [DEBUG] from run_server in main at main.py:90 :
active thread: 'MainThread'

[2010-09-22 10:10:11,254] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_work'

[2010-09-22 10:10:11,255] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_new_judge_connection'

[2010-09-22 10:10:11,255] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work._thread_fetch_task'

[2010-09-22 10:11:46,177] [INFO] from run_server in main at main.py:69 :
orzoj-server started, listening on 9351

[2010-09-22 10:11:48,808] [INFO] from run_server in main at main.py:82 :
connected by '127.0.0.1:54055'

[2010-09-22 10:11:49,020] [INFO] from run in work at work.py:345 :
judge 'orzoj-judge-default' connected successfully

[2010-09-22 10:11:52,841] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-22 10:11:52,842] [ERROR] from accept in snc at snc.py:74 :
socket error: error(4, 'Interrupted system call')

[2010-09-22 10:11:52,842] [DEBUG] from run_server in main at main.py:88 :
waiting for threads, current active count: 4

[2010-09-22 10:11:52,842] [DEBUG] from run_server in main at main.py:90 :
active thread: 'MainThread'

[2010-09-22 10:11:52,843] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_work'

[2010-09-22 10:11:52,843] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_new_judge_connection'

[2010-09-22 10:11:52,843] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work._thread_fetch_task'

[2010-09-22 10:12:23,189] [ERROR] from socket in snc at snc.py:48 :
socket error: error(98, 'Address already in use')

[2010-09-22 10:12:33,343] [ERROR] from socket in snc at snc.py:48 :
socket error: error(98, 'Address already in use')

[2010-09-22 10:12:51,249] [INFO] from run_server in main at main.py:69 :
orzoj-server started, listening on 9351

[2010-09-22 10:12:54,535] [INFO] from run_server in main at main.py:82 :
connected by '127.0.0.1:48285'

[2010-09-22 10:12:54,746] [INFO] from run in work at work.py:345 :
judge 'orzoj-judge-default' connected successfully

[2010-09-22 10:13:06,754] [ERROR] from write in snc at snc.py:123 :
failed to write:
error('SSL error [func SSL_write] [errno: Broken pipe]: error:00000005:lib(0):func(0):DH lib',)

[2010-09-22 10:13:06,755] [WARNING] from run in work at work.py:354 :
failed to serve judge because of network error.

[2010-09-22 10:13:06,755] [INFO] from _clean in work at work.py:133 :
judge 'orzoj-judge-default' disconnected

[2010-09-22 10:13:33,195] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-22 10:13:33,196] [ERROR] from accept in snc at snc.py:74 :
socket error: error(4, 'Interrupted system call')

[2010-09-22 10:13:33,196] [DEBUG] from run_server in main at main.py:88 :
waiting for threads, current active count: 3

[2010-09-22 10:13:33,196] [DEBUG] from run_server in main at main.py:90 :
active thread: 'MainThread'

[2010-09-22 10:13:33,196] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_work'

[2010-09-22 10:13:33,197] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work._thread_fetch_task'

